/* eslint-env mocha */
'use strict'

require('./inject/bitswap')
require('./inject/block')
require('./inject/bootstrap')
require('./inject/config')
require('./inject/dag')
require('./inject/dht')
require('./inject/dns')
require('./inject/files')
require('./inject/id')
require('./inject/key')
require('./inject/mfs')
require('./inject/name')
require('./inject/object')
require('./inject/pin')
require('./inject/ping')
require('./inject/pubsub')
require('./inject/resolve')
require('./inject/version')
