/* eslint-env mocha */
'use strict'

require('./inject/bitswap')
require('./inject/block')
require('./inject/bootstrap')
require('./inject/browser-headers')
require('./inject/config')
require('./inject/dag')
require('./inject/dht')
require('./inject/dns')
require('./inject/files')
require('./inject/id')
require('./inject/key')
require('./inject/mfs/chmod')
require('./inject/mfs/cp')
require('./inject/mfs/flush')
require('./inject/mfs/ls')
require('./inject/mfs/mkdir')
require('./inject/mfs/mv')
require('./inject/mfs/read')
require('./inject/mfs/rm')
require('./inject/mfs/stat')
require('./inject/mfs/touch')
require('./inject/mfs/write')
require('./inject/name')
require('./inject/object')
require('./inject/pin')
require('./inject/ping')
require('./inject/pubsub')
require('./inject/repo')
require('./inject/resolve')
require('./inject/shutdown')
require('./inject/stats')
require('./inject/swarm')
require('./inject/version')
