name: Release RC
on:
  push:
    branches:
      - master

jobs:
  release-rc:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.author.name, 'Github Actions')"
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: Release
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "Github Actions"
          echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc
          echo "$DOCKER_TOKEN" | docker login -u "$DOCKER_USERNAME" --password-stdin
          npm install
          npm run release:rc
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
